export const MOVIE_GENRES = {
  ACTION: 28,
  ADVENTURE: 12,
  ANIMATION: 16,
  COMEDY: 35,
  CRIME: 80,
  DOCUMENTARY: 99,
  DRAMA: 18,
  FAMILY: 10751,
  FANTASY: 14,
  HISTORY: 36,
  HORROR: 27,
  MUSIC: 10402,
  MYSTERY: 9648,
  ROMANCE: 10749,
  SCIENCE_FICTION: 878,
  TV_MOVIE: 10770,
  THRILLER: 53,
  WAR: 10752,
  WESTERN: 37,
} as const;

export const TV_GENRES = {
  ACTION_AND_ADVENTURE: 10759,
  ANIMATION: 16,
  COMEDY: 35,
  CRIME: 80,
  DOCUMENTARY: 99,
  DRAMA: 18,
  FAMILY: 10751,
  KIDS: 10762,
  MYSTERY: 9648,
  NEWS: 10763,
  REALITY: 10764,
  SCI_FI_AND_FANTASY: 10765,
  SOAP: 10766,
  TALK: 10767,
  WAR_AND_POLITICS: 10768,
  WESTERN: 37,
} as const;

export const GENRES_PT_BR = {
  MOVIES: [
    "Ação",
    "Aventura",
    "Animação",
    "Comédia",
    "Crime",
    "Documentário",
    "Drama",
    "Família",
    "Fantasia",
    "História",
    "Terror",
    "Música",
    "Mistério",
    "Romance",
    "Ficção científica",
    "Cinema TV",
    "Thriller",
    "Guerra",
    "Faroeste",
  ],
  TV_SHOWS: [
    "Ação e Aventura",
    "Animação",
    "Comédia",
    "Crime",
    "Documentário",
    "Drama",
    "Família",
    "Kids (Infantil)",
    "Mistério",
    "Notícias",
    "Reality",
    "Ficção científica e Fantasia",
    "Novela (Soap)",
    "Talk",
    "Guerra e Política",
    "Faroeste",
  ],
};

const ALL_GENRES_MAP: Record<number, string> = {
  28: "Ação",
  12: "Aventura",
  16: "Animação",
  35: "Comédia",
  80: "Crime",
  99: "Documentário",
  18: "Drama",
  10751: "Família",
  14: "Fantasia",
  36: "História",
  27: "Terror",
  10402: "Música",
  9648: "Mistério",
  10749: "Romance",
  878: "Ficção Científica",
  10770: "Cinema TV",
  53: "Thriller",
  10752: "Guerra",
  37: "Faroeste",
  10759: "Ação & Aventura",
  10762: "Kids",
  10763: "News",
  10764: "Reality",
  10765: "Sci-Fi & Fantasy",
  10766: "Novela",
  10767: "Talk Show",
  10768: "Guerra & Política",
};

export const getGenreName = (id: number): string => {
  return ALL_GENRES_MAP[id] || "Desconhecido";
};

export const getGenreId = (name: string): number | undefined => {
  const entry = Object.entries(ALL_GENRES_MAP).find(([_, genreName]) => genreName === name);
  return entry ? Number(entry[0]) : undefined;
};
